### PR TITLE
Issue with anonymous guest

### PR DESCRIPTION
**Pull request by geekwright**
Fix error when trying to add entry when not signed in.

### CODE REVIEW

**Comment by mambax7** [comment]
I think, this was solved in my update 1.11 Beta 1: https://github.com/mambax7/gbook/commit/db7223b43aba46641a4457af009b808aea58a3dc

but I'll check your solution...
I was just working on couple of other things before committing it here...

**Comment by geekwright** [comment]
Sorry, I just saw a final release tagged 3 days ago with a problem. Kind of confusing ...

**Comment by mambax7** [comment]
I agree, it is sometimes confusing! That's why like to check often the "fork network" to see who is doing what:
https://github.com/XoopsModules25x/gbook/network

but I like your check better, so I'll use it yours...

**Comment by mambax7** [comment]
And thank you for testing, and providing a solution!  That always helps!!!

**Pull request merged**
